name = "SargassumFromAFAI"
uuid = "db9ac4ac-0b65-4026-8dbd-2bb7cf4c299a"
authors = ["Gage Bonner <gage.bonner@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
