function Base.show(io::IO, x::AFAIParameters)
    print(io, "AFAIParameters[")
    println(io, "window_size_coast_mask = $(x.window_size_coast_mask)")
    println(io, "window_size_median_filter = $(x.window_size_median_filter)")
    println(io, "threshold_median = $(x.threshold_median)")
    println(io, "afai_U0 = $(x.afai_U0)")
    println(io, "afai_L0 = $(x.afai_L0)")
    println(io, "lon_lat_bins_coverage = $(x.lon_lat_bins_coverage)")
    println(io, "distribution_quant = $(x.distribution_quant)")
    print(io, "]")
end

function Base.show(io::IO, x::AFAI)
    print(io, "AFAI[")
    print(io, "$(size(x.afai)[1]*size(x.afai)[2]) pixels, ")
    print(io, "Lon ∈ ")
    show(io, extrema(x.lon))
    print(io, ", Lat ∈ ")
    show(io, extrema(x.lat))
    print(io, ", ")
    print(io, monthname(x.time[1]))
    print(io, " ")
    show(io, Year(x.time[1]).value)
    print(io, "]")
end

function Base.show(io::IO, x::SargassumDistribution)
    print(io, "SargassumDistribution[")
    print(io, "Lon ∈ ")
    show(io, extrema(x.lon))
    print(io, ", Lat ∈ ")
    show(io, extrema(x.lat))
    print(io, ", ")
    print(io, monthname(x.time))
    print(io, " ")
    show(io, Year(x.time).value)
    print(io, "]")
end